name: deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      S_NAME: ${{ secrets.TIMEWEB_FULL_HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push meme_bot
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meme_bot:latest

      - name: Build and push meme_importer
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./cmd/scripts/importer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meme_importer:latest

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TIMEWEB_SSH_KEY }}
          known_hosts: ${{ secrets.TIMEWEB_HOST }}

      - name: Deploy
        run: |
          rsync -avze "ssh -o StrictHostKeyChecking=no" deployments/* "$S_NAME":/root/meme_bot/
          ssh -o StrictHostKeyChecking=no "$S_NAME" /root/meme_bot/start.sh
